import {defineStore} from "pinia";

export const useProductStore = defineStore("ProductStore", {
  state: () => ({
    CartComponent: [
      {
        id: 1,
        promotion: "-75%",
        image: "https://via.placeholder.com/289x289",
        title: "All-Around Safe Block Essence Sun SPF45+",
        product: "All Around Safe Block Sun Milk SPF50+/PA+++",
        rating: "(0)",
        price: "$99.00",
      },
      {
        id: 2,
        promotion: "",
        image: "https://via.placeholder.com/289x289",
        title: "All-Around Safe Block Essence Sun SPF45+",
        product: "All Around Safe Block Sun Milk SPF50+/PA+++",
        rating: "(7)",
        price: "$32.00",
      },
      {
        id: 3,
        promotion: "-25%",
        image: "https://via.placeholder.com/289x289",
        title: "All-Around Safe Block Essence Sun SPF45+",
        product: "All Around Safe Block Sun Milk SPF50+/PA+++",
        rating: "(9)",
        price: "$32.00",
      },
      {
        id: 4,
        promotion: "-10%",
        image: "https://via.placeholder.com/289x289",
        title: "All-Around Safe Block Essence Sun SPF45+",
        product: "All Around Safe Block Sun Milk SPF50+/PA+++",
        rating: "(10)",
        price: "$32.00",
      },
      {
        id: 5,
        promotion: "-50%",
        image: "https://via.placeholder.com/289x289",
        title: "All-Around Safe Block Essence Sun SPF45+",
        product: "All Around Safe Block Sun Milk SPF50+/PA+++",
        rating: "(10)",
        price: "$32.00",
      },
      {
        id: 6,
        promotion: "-10%",
        image: "https://via.placeholder.com/289x289",
        title: "All-Around Safe Block Essence Sun SPF45+",
        product: "All Around Safe Block Sun Milk SPF50+/PA+++",
        rating: "(10)",
        price: "$32.00",
      },
      {
        id: 7,
        promotion: "-75%",
        image: "https://via.placeholder.com/289x289",
        title: "All-Around Safe Block Essence Sun SPF45+",
        product: "All Around Safe Block Sun Milk SPF50+/PA+++",
        rating: "(10)",
        price: "$32.00",
      },
      {
        id: 8,
        promotion: "-25%",
        image: "https://via.placeholder.com/289x289",
        title: "All-Around Safe Block Essence Sun SPF45+",
        product: "All Around Safe Block Sun Milk SPF50+/PA+++",
        rating: "(10)",
        price: "$32.00",
      },
      {
        id: 9,
        promotion: "",
        image: "https://via.placeholder.com/289x289",
        title: "All-Around Safe Block Essence Sun SPF45+",
        product: "All Around Safe Block Sun Milk SPF50+/PA+++",
        rating: "(10)",
        price: "$32.00",
      },
      {
        id: 10,
        promotion: "-25%",
        image: "https://via.placeholder.com/289x289",
        title: "All-Around Safe Block Essence Sun SPF45+",
        product: "All Around Safe Block Sun Milk SPF50+/PA+++",
        rating: "(10)",
        price: "$32.00",
      },
      {
        id: 11,
        promotion: "-10%",
        image: "https://via.placeholder.com/289x289",
        title: "All-Around Safe Block Essence Sun SPF45+",
        product: "All Around Safe Block Sun Milk SPF50+/PA+++",
        rating: "(10)",
        price: "$32.00",
      },
      {
        id: 12,
        promotion: "-75%",
        image: "https://via.placeholder.com/289x289",
        title: "All-Around Safe Block Essence Sun SPF45+",
        product: "All Around Safe Block Sun Milk SPF50+/PA+++",
        rating: "(10)",
        price: "$32.00",
      },
    ],
  }),
  getters: {
    allProducts: (state) => state.products,
    productCount: (state) => state.products.length,
  },
});
